# Netlify build instructions
[build]
    command = "make -C docs/book build"
    publish = "docs/book/book"

[build.environment]
    GO_VERSION = "1.22.5"

# Standard Netlify redirects
[[redirects]]
    from = "https://main--cluster-api-operator.netlify.com/*"
    to = "https://main.cluster-api-operator.sigs.k8s.io/:splat"
    status = 301
    force = true

# HTTP-to-HTTPS rules
[[redirects]]
    from = "http://main.cluster-api-operator.sigs.k8s.io/*"
    to = "https://main.cluster-api-operator.sigs.k8s.io/:splat"
    status = 301
    force = true

[[redirects]]
    from = "http://main--cluster-api-operator.netlify.com/*"
    to = "http://main.cluster-api-operator.sigs.k8s.io/:splat"
    status = 301
    force = true