---
# Cluster API Operator installation control
cluster-api-operator:
  install: true

# Cluster API provider options
core: {}
# cluster-api: {}         # Name, required
#   namespace: ""         # Optional
#   version: ""           # Optional
#   createNamespace: true # Optional
bootstrap: {}
# kubeadm: {}             # Name, required
#   namespace: ""         # Optional
#   version: ""           # Optional
#   createNamespace: true # Optional
controlPlane: {}
# kubeadm: {}             # Name, required
#   namespace: ""         # Optional
#   version: ""           # Optional
#   createNamespace: true # Optional
infrastructure: {}
# docker: {}              # Name, required
#   namespace: ""         # Optional
#   version: ""           # Optional
#   createNamespace: true # Optional
addon: {}
# helm: {}                # Name, required
#   namespace: ""         # Optional
#   version: ""           # Optional
#   createNamespace: true # Optional
ipam: {}
# in-cluster: {}          # Name, required
#   namespace: ""         # Optional
#   version: ""           # Optional
#   createNamespace: true # Optional
manager:
  featureGates: {}
# Configuration for enabling feature gates in different providers
# manager:
#   featureGates:
#     proxmox: # Name of the provider
#       ClusterTopology: true
#     core:
#       ClusterTopology: true
#     kubeadm:
#       ClusterTopology: true
fetchConfig: {}
# ---
# Common configuration secret options
configSecret: {}
# name: global-secret # Required
# namespace: default  # Optional
enableHelmHook: true  # Workaround to avoid ensuring CRDs are installed first
