# aggregates read-only access to the operator provider CRs into the builtin `view`, `edit` and `admin` ClusterRoles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aggregate-view-role
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
rules:
- apiGroups:
  - operator.cluster.x-k8s.io
  resources:
  - addonproviders
  - addonproviders/status
  - bootstrapproviders
  - bootstrapproviders/status
  - controlplaneproviders
  - controlplaneproviders/status
  - coreproviders
  - coreproviders/status
  - infrastructureproviders
  - infrastructureproviders/status
  - ipamproviders
  - ipamproviders/status
  - runtimeextensionproviders
  - runtimeextensionproviders/status
  verbs:
  - get
  - list
  - watch
