//go:build !ignore_autogenerated_core
// +build !ignore_autogenerated_core

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen-v0.27.3. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	v1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	v1alpha2 "sigs.k8s.io/cluster-api-operator/api/v1alpha2"
	v1beta1 "sigs.k8s.io/cluster-api/api/v1beta1"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*BootstrapProvider)(nil), (*v1alpha2.BootstrapProvider)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_BootstrapProvider_To_v1alpha2_BootstrapProvider(a.(*BootstrapProvider), b.(*v1alpha2.BootstrapProvider), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.BootstrapProvider)(nil), (*BootstrapProvider)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_BootstrapProvider_To_v1alpha1_BootstrapProvider(a.(*v1alpha2.BootstrapProvider), b.(*BootstrapProvider), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*BootstrapProviderList)(nil), (*v1alpha2.BootstrapProviderList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_BootstrapProviderList_To_v1alpha2_BootstrapProviderList(a.(*BootstrapProviderList), b.(*v1alpha2.BootstrapProviderList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.BootstrapProviderList)(nil), (*BootstrapProviderList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_BootstrapProviderList_To_v1alpha1_BootstrapProviderList(a.(*v1alpha2.BootstrapProviderList), b.(*BootstrapProviderList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*BootstrapProviderSpec)(nil), (*v1alpha2.BootstrapProviderSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_BootstrapProviderSpec_To_v1alpha2_BootstrapProviderSpec(a.(*BootstrapProviderSpec), b.(*v1alpha2.BootstrapProviderSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.BootstrapProviderSpec)(nil), (*BootstrapProviderSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_BootstrapProviderSpec_To_v1alpha1_BootstrapProviderSpec(a.(*v1alpha2.BootstrapProviderSpec), b.(*BootstrapProviderSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*BootstrapProviderStatus)(nil), (*v1alpha2.BootstrapProviderStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_BootstrapProviderStatus_To_v1alpha2_BootstrapProviderStatus(a.(*BootstrapProviderStatus), b.(*v1alpha2.BootstrapProviderStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.BootstrapProviderStatus)(nil), (*BootstrapProviderStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_BootstrapProviderStatus_To_v1alpha1_BootstrapProviderStatus(a.(*v1alpha2.BootstrapProviderStatus), b.(*BootstrapProviderStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ConfigmapReference)(nil), (*v1alpha2.ConfigmapReference)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ConfigmapReference_To_v1alpha2_ConfigmapReference(a.(*ConfigmapReference), b.(*v1alpha2.ConfigmapReference), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.ConfigmapReference)(nil), (*ConfigmapReference)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ConfigmapReference_To_v1alpha1_ConfigmapReference(a.(*v1alpha2.ConfigmapReference), b.(*ConfigmapReference), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ControlPlaneProvider)(nil), (*v1alpha2.ControlPlaneProvider)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ControlPlaneProvider_To_v1alpha2_ControlPlaneProvider(a.(*ControlPlaneProvider), b.(*v1alpha2.ControlPlaneProvider), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.ControlPlaneProvider)(nil), (*ControlPlaneProvider)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ControlPlaneProvider_To_v1alpha1_ControlPlaneProvider(a.(*v1alpha2.ControlPlaneProvider), b.(*ControlPlaneProvider), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ControlPlaneProviderList)(nil), (*v1alpha2.ControlPlaneProviderList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ControlPlaneProviderList_To_v1alpha2_ControlPlaneProviderList(a.(*ControlPlaneProviderList), b.(*v1alpha2.ControlPlaneProviderList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.ControlPlaneProviderList)(nil), (*ControlPlaneProviderList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ControlPlaneProviderList_To_v1alpha1_ControlPlaneProviderList(a.(*v1alpha2.ControlPlaneProviderList), b.(*ControlPlaneProviderList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ControlPlaneProviderSpec)(nil), (*v1alpha2.ControlPlaneProviderSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ControlPlaneProviderSpec_To_v1alpha2_ControlPlaneProviderSpec(a.(*ControlPlaneProviderSpec), b.(*v1alpha2.ControlPlaneProviderSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.ControlPlaneProviderSpec)(nil), (*ControlPlaneProviderSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ControlPlaneProviderSpec_To_v1alpha1_ControlPlaneProviderSpec(a.(*v1alpha2.ControlPlaneProviderSpec), b.(*ControlPlaneProviderSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ControlPlaneProviderStatus)(nil), (*v1alpha2.ControlPlaneProviderStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ControlPlaneProviderStatus_To_v1alpha2_ControlPlaneProviderStatus(a.(*ControlPlaneProviderStatus), b.(*v1alpha2.ControlPlaneProviderStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.ControlPlaneProviderStatus)(nil), (*ControlPlaneProviderStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ControlPlaneProviderStatus_To_v1alpha1_ControlPlaneProviderStatus(a.(*v1alpha2.ControlPlaneProviderStatus), b.(*ControlPlaneProviderStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CoreProvider)(nil), (*v1alpha2.CoreProvider)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CoreProvider_To_v1alpha2_CoreProvider(a.(*CoreProvider), b.(*v1alpha2.CoreProvider), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.CoreProvider)(nil), (*CoreProvider)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_CoreProvider_To_v1alpha1_CoreProvider(a.(*v1alpha2.CoreProvider), b.(*CoreProvider), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CoreProviderList)(nil), (*v1alpha2.CoreProviderList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CoreProviderList_To_v1alpha2_CoreProviderList(a.(*CoreProviderList), b.(*v1alpha2.CoreProviderList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.CoreProviderList)(nil), (*CoreProviderList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_CoreProviderList_To_v1alpha1_CoreProviderList(a.(*v1alpha2.CoreProviderList), b.(*CoreProviderList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CoreProviderSpec)(nil), (*v1alpha2.CoreProviderSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CoreProviderSpec_To_v1alpha2_CoreProviderSpec(a.(*CoreProviderSpec), b.(*v1alpha2.CoreProviderSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.CoreProviderSpec)(nil), (*CoreProviderSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_CoreProviderSpec_To_v1alpha1_CoreProviderSpec(a.(*v1alpha2.CoreProviderSpec), b.(*CoreProviderSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CoreProviderStatus)(nil), (*v1alpha2.CoreProviderStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CoreProviderStatus_To_v1alpha2_CoreProviderStatus(a.(*CoreProviderStatus), b.(*v1alpha2.CoreProviderStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.CoreProviderStatus)(nil), (*CoreProviderStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_CoreProviderStatus_To_v1alpha1_CoreProviderStatus(a.(*v1alpha2.CoreProviderStatus), b.(*CoreProviderStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DeploymentSpec)(nil), (*v1alpha2.DeploymentSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DeploymentSpec_To_v1alpha2_DeploymentSpec(a.(*DeploymentSpec), b.(*v1alpha2.DeploymentSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.DeploymentSpec)(nil), (*DeploymentSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_DeploymentSpec_To_v1alpha1_DeploymentSpec(a.(*v1alpha2.DeploymentSpec), b.(*DeploymentSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FetchConfiguration)(nil), (*v1alpha2.FetchConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_FetchConfiguration_To_v1alpha2_FetchConfiguration(a.(*FetchConfiguration), b.(*v1alpha2.FetchConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.FetchConfiguration)(nil), (*FetchConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_FetchConfiguration_To_v1alpha1_FetchConfiguration(a.(*v1alpha2.FetchConfiguration), b.(*FetchConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*InfrastructureProvider)(nil), (*v1alpha2.InfrastructureProvider)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_InfrastructureProvider_To_v1alpha2_InfrastructureProvider(a.(*InfrastructureProvider), b.(*v1alpha2.InfrastructureProvider), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.InfrastructureProvider)(nil), (*InfrastructureProvider)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_InfrastructureProvider_To_v1alpha1_InfrastructureProvider(a.(*v1alpha2.InfrastructureProvider), b.(*InfrastructureProvider), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*InfrastructureProviderList)(nil), (*v1alpha2.InfrastructureProviderList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_InfrastructureProviderList_To_v1alpha2_InfrastructureProviderList(a.(*InfrastructureProviderList), b.(*v1alpha2.InfrastructureProviderList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.InfrastructureProviderList)(nil), (*InfrastructureProviderList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_InfrastructureProviderList_To_v1alpha1_InfrastructureProviderList(a.(*v1alpha2.InfrastructureProviderList), b.(*InfrastructureProviderList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*InfrastructureProviderSpec)(nil), (*v1alpha2.InfrastructureProviderSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_InfrastructureProviderSpec_To_v1alpha2_InfrastructureProviderSpec(a.(*InfrastructureProviderSpec), b.(*v1alpha2.InfrastructureProviderSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.InfrastructureProviderSpec)(nil), (*InfrastructureProviderSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_InfrastructureProviderSpec_To_v1alpha1_InfrastructureProviderSpec(a.(*v1alpha2.InfrastructureProviderSpec), b.(*InfrastructureProviderSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*InfrastructureProviderStatus)(nil), (*v1alpha2.InfrastructureProviderStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_InfrastructureProviderStatus_To_v1alpha2_InfrastructureProviderStatus(a.(*InfrastructureProviderStatus), b.(*v1alpha2.InfrastructureProviderStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.InfrastructureProviderStatus)(nil), (*InfrastructureProviderStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_InfrastructureProviderStatus_To_v1alpha1_InfrastructureProviderStatus(a.(*v1alpha2.InfrastructureProviderStatus), b.(*InfrastructureProviderStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ProviderStatus)(nil), (*v1alpha2.ProviderStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ProviderStatus_To_v1alpha2_ProviderStatus(a.(*ProviderStatus), b.(*v1alpha2.ProviderStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.ProviderStatus)(nil), (*ProviderStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ProviderStatus_To_v1alpha1_ProviderStatus(a.(*v1alpha2.ProviderStatus), b.(*ProviderStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*ContainerSpec)(nil), (*v1alpha2.ContainerSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ContainerSpec_To_v1alpha2_ContainerSpec(a.(*ContainerSpec), b.(*v1alpha2.ContainerSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*ManagerSpec)(nil), (*v1alpha2.ManagerSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ManagerSpec_To_v1alpha2_ManagerSpec(a.(*ManagerSpec), b.(*v1alpha2.ManagerSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*ProviderSpec)(nil), (*v1alpha2.ProviderSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ProviderSpec_To_v1alpha2_ProviderSpec(a.(*ProviderSpec), b.(*v1alpha2.ProviderSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1alpha2.ContainerSpec)(nil), (*ContainerSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ContainerSpec_To_v1alpha1_ContainerSpec(a.(*v1alpha2.ContainerSpec), b.(*ContainerSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1alpha2.ManagerSpec)(nil), (*ManagerSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ManagerSpec_To_v1alpha1_ManagerSpec(a.(*v1alpha2.ManagerSpec), b.(*ManagerSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1alpha2.ProviderSpec)(nil), (*ProviderSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ProviderSpec_To_v1alpha1_ProviderSpec(a.(*v1alpha2.ProviderSpec), b.(*ProviderSpec), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_BootstrapProvider_To_v1alpha2_BootstrapProvider(in *BootstrapProvider, out *v1alpha2.BootstrapProvider, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_BootstrapProviderSpec_To_v1alpha2_BootstrapProviderSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_BootstrapProviderStatus_To_v1alpha2_BootstrapProviderStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_BootstrapProvider_To_v1alpha2_BootstrapProvider is an autogenerated conversion function.
func Convert_v1alpha1_BootstrapProvider_To_v1alpha2_BootstrapProvider(in *BootstrapProvider, out *v1alpha2.BootstrapProvider, s conversion.Scope) error {
	return autoConvert_v1alpha1_BootstrapProvider_To_v1alpha2_BootstrapProvider(in, out, s)
}

func autoConvert_v1alpha2_BootstrapProvider_To_v1alpha1_BootstrapProvider(in *v1alpha2.BootstrapProvider, out *BootstrapProvider, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha2_BootstrapProviderSpec_To_v1alpha1_BootstrapProviderSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha2_BootstrapProviderStatus_To_v1alpha1_BootstrapProviderStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_BootstrapProvider_To_v1alpha1_BootstrapProvider is an autogenerated conversion function.
func Convert_v1alpha2_BootstrapProvider_To_v1alpha1_BootstrapProvider(in *v1alpha2.BootstrapProvider, out *BootstrapProvider, s conversion.Scope) error {
	return autoConvert_v1alpha2_BootstrapProvider_To_v1alpha1_BootstrapProvider(in, out, s)
}

func autoConvert_v1alpha1_BootstrapProviderList_To_v1alpha2_BootstrapProviderList(in *BootstrapProviderList, out *v1alpha2.BootstrapProviderList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1alpha2.BootstrapProvider, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_BootstrapProvider_To_v1alpha2_BootstrapProvider(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha1_BootstrapProviderList_To_v1alpha2_BootstrapProviderList is an autogenerated conversion function.
func Convert_v1alpha1_BootstrapProviderList_To_v1alpha2_BootstrapProviderList(in *BootstrapProviderList, out *v1alpha2.BootstrapProviderList, s conversion.Scope) error {
	return autoConvert_v1alpha1_BootstrapProviderList_To_v1alpha2_BootstrapProviderList(in, out, s)
}

func autoConvert_v1alpha2_BootstrapProviderList_To_v1alpha1_BootstrapProviderList(in *v1alpha2.BootstrapProviderList, out *BootstrapProviderList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BootstrapProvider, len(*in))
		for i := range *in {
			if err := Convert_v1alpha2_BootstrapProvider_To_v1alpha1_BootstrapProvider(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha2_BootstrapProviderList_To_v1alpha1_BootstrapProviderList is an autogenerated conversion function.
func Convert_v1alpha2_BootstrapProviderList_To_v1alpha1_BootstrapProviderList(in *v1alpha2.BootstrapProviderList, out *BootstrapProviderList, s conversion.Scope) error {
	return autoConvert_v1alpha2_BootstrapProviderList_To_v1alpha1_BootstrapProviderList(in, out, s)
}

func autoConvert_v1alpha1_BootstrapProviderSpec_To_v1alpha2_BootstrapProviderSpec(in *BootstrapProviderSpec, out *v1alpha2.BootstrapProviderSpec, s conversion.Scope) error {
	if err := Convert_v1alpha1_ProviderSpec_To_v1alpha2_ProviderSpec(&in.ProviderSpec, &out.ProviderSpec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_BootstrapProviderSpec_To_v1alpha2_BootstrapProviderSpec is an autogenerated conversion function.
func Convert_v1alpha1_BootstrapProviderSpec_To_v1alpha2_BootstrapProviderSpec(in *BootstrapProviderSpec, out *v1alpha2.BootstrapProviderSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_BootstrapProviderSpec_To_v1alpha2_BootstrapProviderSpec(in, out, s)
}

func autoConvert_v1alpha2_BootstrapProviderSpec_To_v1alpha1_BootstrapProviderSpec(in *v1alpha2.BootstrapProviderSpec, out *BootstrapProviderSpec, s conversion.Scope) error {
	if err := Convert_v1alpha2_ProviderSpec_To_v1alpha1_ProviderSpec(&in.ProviderSpec, &out.ProviderSpec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_BootstrapProviderSpec_To_v1alpha1_BootstrapProviderSpec is an autogenerated conversion function.
func Convert_v1alpha2_BootstrapProviderSpec_To_v1alpha1_BootstrapProviderSpec(in *v1alpha2.BootstrapProviderSpec, out *BootstrapProviderSpec, s conversion.Scope) error {
	return autoConvert_v1alpha2_BootstrapProviderSpec_To_v1alpha1_BootstrapProviderSpec(in, out, s)
}

func autoConvert_v1alpha1_BootstrapProviderStatus_To_v1alpha2_BootstrapProviderStatus(in *BootstrapProviderStatus, out *v1alpha2.BootstrapProviderStatus, s conversion.Scope) error {
	if err := Convert_v1alpha1_ProviderStatus_To_v1alpha2_ProviderStatus(&in.ProviderStatus, &out.ProviderStatus, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_BootstrapProviderStatus_To_v1alpha2_BootstrapProviderStatus is an autogenerated conversion function.
func Convert_v1alpha1_BootstrapProviderStatus_To_v1alpha2_BootstrapProviderStatus(in *BootstrapProviderStatus, out *v1alpha2.BootstrapProviderStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_BootstrapProviderStatus_To_v1alpha2_BootstrapProviderStatus(in, out, s)
}

func autoConvert_v1alpha2_BootstrapProviderStatus_To_v1alpha1_BootstrapProviderStatus(in *v1alpha2.BootstrapProviderStatus, out *BootstrapProviderStatus, s conversion.Scope) error {
	if err := Convert_v1alpha2_ProviderStatus_To_v1alpha1_ProviderStatus(&in.ProviderStatus, &out.ProviderStatus, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_BootstrapProviderStatus_To_v1alpha1_BootstrapProviderStatus is an autogenerated conversion function.
func Convert_v1alpha2_BootstrapProviderStatus_To_v1alpha1_BootstrapProviderStatus(in *v1alpha2.BootstrapProviderStatus, out *BootstrapProviderStatus, s conversion.Scope) error {
	return autoConvert_v1alpha2_BootstrapProviderStatus_To_v1alpha1_BootstrapProviderStatus(in, out, s)
}

func autoConvert_v1alpha1_ConfigmapReference_To_v1alpha2_ConfigmapReference(in *ConfigmapReference, out *v1alpha2.ConfigmapReference, s conversion.Scope) error {
	out.Name = in.Name
	out.Namespace = in.Namespace
	return nil
}

// Convert_v1alpha1_ConfigmapReference_To_v1alpha2_ConfigmapReference is an autogenerated conversion function.
func Convert_v1alpha1_ConfigmapReference_To_v1alpha2_ConfigmapReference(in *ConfigmapReference, out *v1alpha2.ConfigmapReference, s conversion.Scope) error {
	return autoConvert_v1alpha1_ConfigmapReference_To_v1alpha2_ConfigmapReference(in, out, s)
}

func autoConvert_v1alpha2_ConfigmapReference_To_v1alpha1_ConfigmapReference(in *v1alpha2.ConfigmapReference, out *ConfigmapReference, s conversion.Scope) error {
	out.Name = in.Name
	out.Namespace = in.Namespace
	return nil
}

// Convert_v1alpha2_ConfigmapReference_To_v1alpha1_ConfigmapReference is an autogenerated conversion function.
func Convert_v1alpha2_ConfigmapReference_To_v1alpha1_ConfigmapReference(in *v1alpha2.ConfigmapReference, out *ConfigmapReference, s conversion.Scope) error {
	return autoConvert_v1alpha2_ConfigmapReference_To_v1alpha1_ConfigmapReference(in, out, s)
}

func autoConvert_v1alpha1_ContainerSpec_To_v1alpha2_ContainerSpec(in *ContainerSpec, out *v1alpha2.ContainerSpec, s conversion.Scope) error {
	out.Name = in.Name
	// WARNING: in.Image requires manual conversion: does not exist in peer-type
	out.Args = *(*map[string]string)(unsafe.Pointer(&in.Args))
	out.Env = *(*[]v1.EnvVar)(unsafe.Pointer(&in.Env))
	out.Resources = (*v1.ResourceRequirements)(unsafe.Pointer(in.Resources))
	out.Command = *(*[]string)(unsafe.Pointer(&in.Command))
	return nil
}

func autoConvert_v1alpha2_ContainerSpec_To_v1alpha1_ContainerSpec(in *v1alpha2.ContainerSpec, out *ContainerSpec, s conversion.Scope) error {
	out.Name = in.Name
	// WARNING: in.ImageURL requires manual conversion: does not exist in peer-type
	out.Args = *(*map[string]string)(unsafe.Pointer(&in.Args))
	out.Env = *(*[]v1.EnvVar)(unsafe.Pointer(&in.Env))
	out.Resources = (*v1.ResourceRequirements)(unsafe.Pointer(in.Resources))
	out.Command = *(*[]string)(unsafe.Pointer(&in.Command))
	return nil
}

func autoConvert_v1alpha1_ControlPlaneProvider_To_v1alpha2_ControlPlaneProvider(in *ControlPlaneProvider, out *v1alpha2.ControlPlaneProvider, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_ControlPlaneProviderSpec_To_v1alpha2_ControlPlaneProviderSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ControlPlaneProviderStatus_To_v1alpha2_ControlPlaneProviderStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ControlPlaneProvider_To_v1alpha2_ControlPlaneProvider is an autogenerated conversion function.
func Convert_v1alpha1_ControlPlaneProvider_To_v1alpha2_ControlPlaneProvider(in *ControlPlaneProvider, out *v1alpha2.ControlPlaneProvider, s conversion.Scope) error {
	return autoConvert_v1alpha1_ControlPlaneProvider_To_v1alpha2_ControlPlaneProvider(in, out, s)
}

func autoConvert_v1alpha2_ControlPlaneProvider_To_v1alpha1_ControlPlaneProvider(in *v1alpha2.ControlPlaneProvider, out *ControlPlaneProvider, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha2_ControlPlaneProviderSpec_To_v1alpha1_ControlPlaneProviderSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha2_ControlPlaneProviderStatus_To_v1alpha1_ControlPlaneProviderStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_ControlPlaneProvider_To_v1alpha1_ControlPlaneProvider is an autogenerated conversion function.
func Convert_v1alpha2_ControlPlaneProvider_To_v1alpha1_ControlPlaneProvider(in *v1alpha2.ControlPlaneProvider, out *ControlPlaneProvider, s conversion.Scope) error {
	return autoConvert_v1alpha2_ControlPlaneProvider_To_v1alpha1_ControlPlaneProvider(in, out, s)
}

func autoConvert_v1alpha1_ControlPlaneProviderList_To_v1alpha2_ControlPlaneProviderList(in *ControlPlaneProviderList, out *v1alpha2.ControlPlaneProviderList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1alpha2.ControlPlaneProvider, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_ControlPlaneProvider_To_v1alpha2_ControlPlaneProvider(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha1_ControlPlaneProviderList_To_v1alpha2_ControlPlaneProviderList is an autogenerated conversion function.
func Convert_v1alpha1_ControlPlaneProviderList_To_v1alpha2_ControlPlaneProviderList(in *ControlPlaneProviderList, out *v1alpha2.ControlPlaneProviderList, s conversion.Scope) error {
	return autoConvert_v1alpha1_ControlPlaneProviderList_To_v1alpha2_ControlPlaneProviderList(in, out, s)
}

func autoConvert_v1alpha2_ControlPlaneProviderList_To_v1alpha1_ControlPlaneProviderList(in *v1alpha2.ControlPlaneProviderList, out *ControlPlaneProviderList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ControlPlaneProvider, len(*in))
		for i := range *in {
			if err := Convert_v1alpha2_ControlPlaneProvider_To_v1alpha1_ControlPlaneProvider(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha2_ControlPlaneProviderList_To_v1alpha1_ControlPlaneProviderList is an autogenerated conversion function.
func Convert_v1alpha2_ControlPlaneProviderList_To_v1alpha1_ControlPlaneProviderList(in *v1alpha2.ControlPlaneProviderList, out *ControlPlaneProviderList, s conversion.Scope) error {
	return autoConvert_v1alpha2_ControlPlaneProviderList_To_v1alpha1_ControlPlaneProviderList(in, out, s)
}

func autoConvert_v1alpha1_ControlPlaneProviderSpec_To_v1alpha2_ControlPlaneProviderSpec(in *ControlPlaneProviderSpec, out *v1alpha2.ControlPlaneProviderSpec, s conversion.Scope) error {
	if err := Convert_v1alpha1_ProviderSpec_To_v1alpha2_ProviderSpec(&in.ProviderSpec, &out.ProviderSpec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ControlPlaneProviderSpec_To_v1alpha2_ControlPlaneProviderSpec is an autogenerated conversion function.
func Convert_v1alpha1_ControlPlaneProviderSpec_To_v1alpha2_ControlPlaneProviderSpec(in *ControlPlaneProviderSpec, out *v1alpha2.ControlPlaneProviderSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_ControlPlaneProviderSpec_To_v1alpha2_ControlPlaneProviderSpec(in, out, s)
}

func autoConvert_v1alpha2_ControlPlaneProviderSpec_To_v1alpha1_ControlPlaneProviderSpec(in *v1alpha2.ControlPlaneProviderSpec, out *ControlPlaneProviderSpec, s conversion.Scope) error {
	if err := Convert_v1alpha2_ProviderSpec_To_v1alpha1_ProviderSpec(&in.ProviderSpec, &out.ProviderSpec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_ControlPlaneProviderSpec_To_v1alpha1_ControlPlaneProviderSpec is an autogenerated conversion function.
func Convert_v1alpha2_ControlPlaneProviderSpec_To_v1alpha1_ControlPlaneProviderSpec(in *v1alpha2.ControlPlaneProviderSpec, out *ControlPlaneProviderSpec, s conversion.Scope) error {
	return autoConvert_v1alpha2_ControlPlaneProviderSpec_To_v1alpha1_ControlPlaneProviderSpec(in, out, s)
}

func autoConvert_v1alpha1_ControlPlaneProviderStatus_To_v1alpha2_ControlPlaneProviderStatus(in *ControlPlaneProviderStatus, out *v1alpha2.ControlPlaneProviderStatus, s conversion.Scope) error {
	if err := Convert_v1alpha1_ProviderStatus_To_v1alpha2_ProviderStatus(&in.ProviderStatus, &out.ProviderStatus, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ControlPlaneProviderStatus_To_v1alpha2_ControlPlaneProviderStatus is an autogenerated conversion function.
func Convert_v1alpha1_ControlPlaneProviderStatus_To_v1alpha2_ControlPlaneProviderStatus(in *ControlPlaneProviderStatus, out *v1alpha2.ControlPlaneProviderStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_ControlPlaneProviderStatus_To_v1alpha2_ControlPlaneProviderStatus(in, out, s)
}

func autoConvert_v1alpha2_ControlPlaneProviderStatus_To_v1alpha1_ControlPlaneProviderStatus(in *v1alpha2.ControlPlaneProviderStatus, out *ControlPlaneProviderStatus, s conversion.Scope) error {
	if err := Convert_v1alpha2_ProviderStatus_To_v1alpha1_ProviderStatus(&in.ProviderStatus, &out.ProviderStatus, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_ControlPlaneProviderStatus_To_v1alpha1_ControlPlaneProviderStatus is an autogenerated conversion function.
func Convert_v1alpha2_ControlPlaneProviderStatus_To_v1alpha1_ControlPlaneProviderStatus(in *v1alpha2.ControlPlaneProviderStatus, out *ControlPlaneProviderStatus, s conversion.Scope) error {
	return autoConvert_v1alpha2_ControlPlaneProviderStatus_To_v1alpha1_ControlPlaneProviderStatus(in, out, s)
}

func autoConvert_v1alpha1_CoreProvider_To_v1alpha2_CoreProvider(in *CoreProvider, out *v1alpha2.CoreProvider, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_CoreProviderSpec_To_v1alpha2_CoreProviderSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_CoreProviderStatus_To_v1alpha2_CoreProviderStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_CoreProvider_To_v1alpha2_CoreProvider is an autogenerated conversion function.
func Convert_v1alpha1_CoreProvider_To_v1alpha2_CoreProvider(in *CoreProvider, out *v1alpha2.CoreProvider, s conversion.Scope) error {
	return autoConvert_v1alpha1_CoreProvider_To_v1alpha2_CoreProvider(in, out, s)
}

func autoConvert_v1alpha2_CoreProvider_To_v1alpha1_CoreProvider(in *v1alpha2.CoreProvider, out *CoreProvider, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha2_CoreProviderSpec_To_v1alpha1_CoreProviderSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha2_CoreProviderStatus_To_v1alpha1_CoreProviderStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_CoreProvider_To_v1alpha1_CoreProvider is an autogenerated conversion function.
func Convert_v1alpha2_CoreProvider_To_v1alpha1_CoreProvider(in *v1alpha2.CoreProvider, out *CoreProvider, s conversion.Scope) error {
	return autoConvert_v1alpha2_CoreProvider_To_v1alpha1_CoreProvider(in, out, s)
}

func autoConvert_v1alpha1_CoreProviderList_To_v1alpha2_CoreProviderList(in *CoreProviderList, out *v1alpha2.CoreProviderList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1alpha2.CoreProvider, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_CoreProvider_To_v1alpha2_CoreProvider(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha1_CoreProviderList_To_v1alpha2_CoreProviderList is an autogenerated conversion function.
func Convert_v1alpha1_CoreProviderList_To_v1alpha2_CoreProviderList(in *CoreProviderList, out *v1alpha2.CoreProviderList, s conversion.Scope) error {
	return autoConvert_v1alpha1_CoreProviderList_To_v1alpha2_CoreProviderList(in, out, s)
}

func autoConvert_v1alpha2_CoreProviderList_To_v1alpha1_CoreProviderList(in *v1alpha2.CoreProviderList, out *CoreProviderList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CoreProvider, len(*in))
		for i := range *in {
			if err := Convert_v1alpha2_CoreProvider_To_v1alpha1_CoreProvider(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha2_CoreProviderList_To_v1alpha1_CoreProviderList is an autogenerated conversion function.
func Convert_v1alpha2_CoreProviderList_To_v1alpha1_CoreProviderList(in *v1alpha2.CoreProviderList, out *CoreProviderList, s conversion.Scope) error {
	return autoConvert_v1alpha2_CoreProviderList_To_v1alpha1_CoreProviderList(in, out, s)
}

func autoConvert_v1alpha1_CoreProviderSpec_To_v1alpha2_CoreProviderSpec(in *CoreProviderSpec, out *v1alpha2.CoreProviderSpec, s conversion.Scope) error {
	if err := Convert_v1alpha1_ProviderSpec_To_v1alpha2_ProviderSpec(&in.ProviderSpec, &out.ProviderSpec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_CoreProviderSpec_To_v1alpha2_CoreProviderSpec is an autogenerated conversion function.
func Convert_v1alpha1_CoreProviderSpec_To_v1alpha2_CoreProviderSpec(in *CoreProviderSpec, out *v1alpha2.CoreProviderSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_CoreProviderSpec_To_v1alpha2_CoreProviderSpec(in, out, s)
}

func autoConvert_v1alpha2_CoreProviderSpec_To_v1alpha1_CoreProviderSpec(in *v1alpha2.CoreProviderSpec, out *CoreProviderSpec, s conversion.Scope) error {
	if err := Convert_v1alpha2_ProviderSpec_To_v1alpha1_ProviderSpec(&in.ProviderSpec, &out.ProviderSpec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_CoreProviderSpec_To_v1alpha1_CoreProviderSpec is an autogenerated conversion function.
func Convert_v1alpha2_CoreProviderSpec_To_v1alpha1_CoreProviderSpec(in *v1alpha2.CoreProviderSpec, out *CoreProviderSpec, s conversion.Scope) error {
	return autoConvert_v1alpha2_CoreProviderSpec_To_v1alpha1_CoreProviderSpec(in, out, s)
}

func autoConvert_v1alpha1_CoreProviderStatus_To_v1alpha2_CoreProviderStatus(in *CoreProviderStatus, out *v1alpha2.CoreProviderStatus, s conversion.Scope) error {
	if err := Convert_v1alpha1_ProviderStatus_To_v1alpha2_ProviderStatus(&in.ProviderStatus, &out.ProviderStatus, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_CoreProviderStatus_To_v1alpha2_CoreProviderStatus is an autogenerated conversion function.
func Convert_v1alpha1_CoreProviderStatus_To_v1alpha2_CoreProviderStatus(in *CoreProviderStatus, out *v1alpha2.CoreProviderStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_CoreProviderStatus_To_v1alpha2_CoreProviderStatus(in, out, s)
}

func autoConvert_v1alpha2_CoreProviderStatus_To_v1alpha1_CoreProviderStatus(in *v1alpha2.CoreProviderStatus, out *CoreProviderStatus, s conversion.Scope) error {
	if err := Convert_v1alpha2_ProviderStatus_To_v1alpha1_ProviderStatus(&in.ProviderStatus, &out.ProviderStatus, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_CoreProviderStatus_To_v1alpha1_CoreProviderStatus is an autogenerated conversion function.
func Convert_v1alpha2_CoreProviderStatus_To_v1alpha1_CoreProviderStatus(in *v1alpha2.CoreProviderStatus, out *CoreProviderStatus, s conversion.Scope) error {
	return autoConvert_v1alpha2_CoreProviderStatus_To_v1alpha1_CoreProviderStatus(in, out, s)
}

func autoConvert_v1alpha1_DeploymentSpec_To_v1alpha2_DeploymentSpec(in *DeploymentSpec, out *v1alpha2.DeploymentSpec, s conversion.Scope) error {
	out.Replicas = (*int)(unsafe.Pointer(in.Replicas))
	out.NodeSelector = *(*map[string]string)(unsafe.Pointer(&in.NodeSelector))
	out.Tolerations = *(*[]v1.Toleration)(unsafe.Pointer(&in.Tolerations))
	out.Affinity = (*v1.Affinity)(unsafe.Pointer(in.Affinity))
	if in.Containers != nil {
		in, out := &in.Containers, &out.Containers
		*out = make([]v1alpha2.ContainerSpec, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_ContainerSpec_To_v1alpha2_ContainerSpec(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Containers = nil
	}
	out.ServiceAccountName = in.ServiceAccountName
	out.ImagePullSecrets = *(*[]v1.LocalObjectReference)(unsafe.Pointer(&in.ImagePullSecrets))
	return nil
}

// Convert_v1alpha1_DeploymentSpec_To_v1alpha2_DeploymentSpec is an autogenerated conversion function.
func Convert_v1alpha1_DeploymentSpec_To_v1alpha2_DeploymentSpec(in *DeploymentSpec, out *v1alpha2.DeploymentSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_DeploymentSpec_To_v1alpha2_DeploymentSpec(in, out, s)
}

func autoConvert_v1alpha2_DeploymentSpec_To_v1alpha1_DeploymentSpec(in *v1alpha2.DeploymentSpec, out *DeploymentSpec, s conversion.Scope) error {
	out.Replicas = (*int)(unsafe.Pointer(in.Replicas))
	out.NodeSelector = *(*map[string]string)(unsafe.Pointer(&in.NodeSelector))
	out.Tolerations = *(*[]v1.Toleration)(unsafe.Pointer(&in.Tolerations))
	out.Affinity = (*v1.Affinity)(unsafe.Pointer(in.Affinity))
	if in.Containers != nil {
		in, out := &in.Containers, &out.Containers
		*out = make([]ContainerSpec, len(*in))
		for i := range *in {
			if err := Convert_v1alpha2_ContainerSpec_To_v1alpha1_ContainerSpec(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Containers = nil
	}
	out.ServiceAccountName = in.ServiceAccountName
	out.ImagePullSecrets = *(*[]v1.LocalObjectReference)(unsafe.Pointer(&in.ImagePullSecrets))
	return nil
}

// Convert_v1alpha2_DeploymentSpec_To_v1alpha1_DeploymentSpec is an autogenerated conversion function.
func Convert_v1alpha2_DeploymentSpec_To_v1alpha1_DeploymentSpec(in *v1alpha2.DeploymentSpec, out *DeploymentSpec, s conversion.Scope) error {
	return autoConvert_v1alpha2_DeploymentSpec_To_v1alpha1_DeploymentSpec(in, out, s)
}

func autoConvert_v1alpha1_FetchConfiguration_To_v1alpha2_FetchConfiguration(in *FetchConfiguration, out *v1alpha2.FetchConfiguration, s conversion.Scope) error {
	out.URL = in.URL
	out.Selector = (*metav1.LabelSelector)(unsafe.Pointer(in.Selector))
	return nil
}

// Convert_v1alpha1_FetchConfiguration_To_v1alpha2_FetchConfiguration is an autogenerated conversion function.
func Convert_v1alpha1_FetchConfiguration_To_v1alpha2_FetchConfiguration(in *FetchConfiguration, out *v1alpha2.FetchConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_FetchConfiguration_To_v1alpha2_FetchConfiguration(in, out, s)
}

func autoConvert_v1alpha2_FetchConfiguration_To_v1alpha1_FetchConfiguration(in *v1alpha2.FetchConfiguration, out *FetchConfiguration, s conversion.Scope) error {
	out.URL = in.URL
	out.Selector = (*metav1.LabelSelector)(unsafe.Pointer(in.Selector))
	return nil
}

// Convert_v1alpha2_FetchConfiguration_To_v1alpha1_FetchConfiguration is an autogenerated conversion function.
func Convert_v1alpha2_FetchConfiguration_To_v1alpha1_FetchConfiguration(in *v1alpha2.FetchConfiguration, out *FetchConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha2_FetchConfiguration_To_v1alpha1_FetchConfiguration(in, out, s)
}

func autoConvert_v1alpha1_InfrastructureProvider_To_v1alpha2_InfrastructureProvider(in *InfrastructureProvider, out *v1alpha2.InfrastructureProvider, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_InfrastructureProviderSpec_To_v1alpha2_InfrastructureProviderSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_InfrastructureProviderStatus_To_v1alpha2_InfrastructureProviderStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_InfrastructureProvider_To_v1alpha2_InfrastructureProvider is an autogenerated conversion function.
func Convert_v1alpha1_InfrastructureProvider_To_v1alpha2_InfrastructureProvider(in *InfrastructureProvider, out *v1alpha2.InfrastructureProvider, s conversion.Scope) error {
	return autoConvert_v1alpha1_InfrastructureProvider_To_v1alpha2_InfrastructureProvider(in, out, s)
}

func autoConvert_v1alpha2_InfrastructureProvider_To_v1alpha1_InfrastructureProvider(in *v1alpha2.InfrastructureProvider, out *InfrastructureProvider, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha2_InfrastructureProviderSpec_To_v1alpha1_InfrastructureProviderSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha2_InfrastructureProviderStatus_To_v1alpha1_InfrastructureProviderStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_InfrastructureProvider_To_v1alpha1_InfrastructureProvider is an autogenerated conversion function.
func Convert_v1alpha2_InfrastructureProvider_To_v1alpha1_InfrastructureProvider(in *v1alpha2.InfrastructureProvider, out *InfrastructureProvider, s conversion.Scope) error {
	return autoConvert_v1alpha2_InfrastructureProvider_To_v1alpha1_InfrastructureProvider(in, out, s)
}

func autoConvert_v1alpha1_InfrastructureProviderList_To_v1alpha2_InfrastructureProviderList(in *InfrastructureProviderList, out *v1alpha2.InfrastructureProviderList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1alpha2.InfrastructureProvider, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_InfrastructureProvider_To_v1alpha2_InfrastructureProvider(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha1_InfrastructureProviderList_To_v1alpha2_InfrastructureProviderList is an autogenerated conversion function.
func Convert_v1alpha1_InfrastructureProviderList_To_v1alpha2_InfrastructureProviderList(in *InfrastructureProviderList, out *v1alpha2.InfrastructureProviderList, s conversion.Scope) error {
	return autoConvert_v1alpha1_InfrastructureProviderList_To_v1alpha2_InfrastructureProviderList(in, out, s)
}

func autoConvert_v1alpha2_InfrastructureProviderList_To_v1alpha1_InfrastructureProviderList(in *v1alpha2.InfrastructureProviderList, out *InfrastructureProviderList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InfrastructureProvider, len(*in))
		for i := range *in {
			if err := Convert_v1alpha2_InfrastructureProvider_To_v1alpha1_InfrastructureProvider(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha2_InfrastructureProviderList_To_v1alpha1_InfrastructureProviderList is an autogenerated conversion function.
func Convert_v1alpha2_InfrastructureProviderList_To_v1alpha1_InfrastructureProviderList(in *v1alpha2.InfrastructureProviderList, out *InfrastructureProviderList, s conversion.Scope) error {
	return autoConvert_v1alpha2_InfrastructureProviderList_To_v1alpha1_InfrastructureProviderList(in, out, s)
}

func autoConvert_v1alpha1_InfrastructureProviderSpec_To_v1alpha2_InfrastructureProviderSpec(in *InfrastructureProviderSpec, out *v1alpha2.InfrastructureProviderSpec, s conversion.Scope) error {
	if err := Convert_v1alpha1_ProviderSpec_To_v1alpha2_ProviderSpec(&in.ProviderSpec, &out.ProviderSpec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_InfrastructureProviderSpec_To_v1alpha2_InfrastructureProviderSpec is an autogenerated conversion function.
func Convert_v1alpha1_InfrastructureProviderSpec_To_v1alpha2_InfrastructureProviderSpec(in *InfrastructureProviderSpec, out *v1alpha2.InfrastructureProviderSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_InfrastructureProviderSpec_To_v1alpha2_InfrastructureProviderSpec(in, out, s)
}

func autoConvert_v1alpha2_InfrastructureProviderSpec_To_v1alpha1_InfrastructureProviderSpec(in *v1alpha2.InfrastructureProviderSpec, out *InfrastructureProviderSpec, s conversion.Scope) error {
	if err := Convert_v1alpha2_ProviderSpec_To_v1alpha1_ProviderSpec(&in.ProviderSpec, &out.ProviderSpec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_InfrastructureProviderSpec_To_v1alpha1_InfrastructureProviderSpec is an autogenerated conversion function.
func Convert_v1alpha2_InfrastructureProviderSpec_To_v1alpha1_InfrastructureProviderSpec(in *v1alpha2.InfrastructureProviderSpec, out *InfrastructureProviderSpec, s conversion.Scope) error {
	return autoConvert_v1alpha2_InfrastructureProviderSpec_To_v1alpha1_InfrastructureProviderSpec(in, out, s)
}

func autoConvert_v1alpha1_InfrastructureProviderStatus_To_v1alpha2_InfrastructureProviderStatus(in *InfrastructureProviderStatus, out *v1alpha2.InfrastructureProviderStatus, s conversion.Scope) error {
	if err := Convert_v1alpha1_ProviderStatus_To_v1alpha2_ProviderStatus(&in.ProviderStatus, &out.ProviderStatus, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_InfrastructureProviderStatus_To_v1alpha2_InfrastructureProviderStatus is an autogenerated conversion function.
func Convert_v1alpha1_InfrastructureProviderStatus_To_v1alpha2_InfrastructureProviderStatus(in *InfrastructureProviderStatus, out *v1alpha2.InfrastructureProviderStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_InfrastructureProviderStatus_To_v1alpha2_InfrastructureProviderStatus(in, out, s)
}

func autoConvert_v1alpha2_InfrastructureProviderStatus_To_v1alpha1_InfrastructureProviderStatus(in *v1alpha2.InfrastructureProviderStatus, out *InfrastructureProviderStatus, s conversion.Scope) error {
	if err := Convert_v1alpha2_ProviderStatus_To_v1alpha1_ProviderStatus(&in.ProviderStatus, &out.ProviderStatus, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_InfrastructureProviderStatus_To_v1alpha1_InfrastructureProviderStatus is an autogenerated conversion function.
func Convert_v1alpha2_InfrastructureProviderStatus_To_v1alpha1_InfrastructureProviderStatus(in *v1alpha2.InfrastructureProviderStatus, out *InfrastructureProviderStatus, s conversion.Scope) error {
	return autoConvert_v1alpha2_InfrastructureProviderStatus_To_v1alpha1_InfrastructureProviderStatus(in, out, s)
}

func autoConvert_v1alpha1_ManagerSpec_To_v1alpha2_ManagerSpec(in *ManagerSpec, out *v1alpha2.ManagerSpec, s conversion.Scope) error {
	// WARNING: in.ControllerManagerConfigurationSpec requires manual conversion: does not exist in peer-type
	out.ProfilerAddress = in.ProfilerAddress
	out.MaxConcurrentReconciles = in.MaxConcurrentReconciles
	out.Verbosity = in.Verbosity
	out.FeatureGates = *(*map[string]bool)(unsafe.Pointer(&in.FeatureGates))
	return nil
}

func autoConvert_v1alpha2_ManagerSpec_To_v1alpha1_ManagerSpec(in *v1alpha2.ManagerSpec, out *ManagerSpec, s conversion.Scope) error {
	// WARNING: in.ControllerManagerConfiguration requires manual conversion: does not exist in peer-type
	out.ProfilerAddress = in.ProfilerAddress
	out.MaxConcurrentReconciles = in.MaxConcurrentReconciles
	out.Verbosity = in.Verbosity
	out.FeatureGates = *(*map[string]bool)(unsafe.Pointer(&in.FeatureGates))
	return nil
}

func autoConvert_v1alpha1_ProviderSpec_To_v1alpha2_ProviderSpec(in *ProviderSpec, out *v1alpha2.ProviderSpec, s conversion.Scope) error {
	out.Version = in.Version
	if in.Manager != nil {
		in, out := &in.Manager, &out.Manager
		*out = new(v1alpha2.ManagerSpec)
		if err := Convert_v1alpha1_ManagerSpec_To_v1alpha2_ManagerSpec(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.Manager = nil
	}
	if in.Deployment != nil {
		in, out := &in.Deployment, &out.Deployment
		*out = new(v1alpha2.DeploymentSpec)
		if err := Convert_v1alpha1_DeploymentSpec_To_v1alpha2_DeploymentSpec(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.Deployment = nil
	}
	// WARNING: in.SecretName requires manual conversion: does not exist in peer-type
	// WARNING: in.SecretNamespace requires manual conversion: does not exist in peer-type
	out.FetchConfig = (*v1alpha2.FetchConfiguration)(unsafe.Pointer(in.FetchConfig))
	out.AdditionalManifestsRef = (*v1alpha2.ConfigmapReference)(unsafe.Pointer(in.AdditionalManifestsRef))
	return nil
}

func autoConvert_v1alpha2_ProviderSpec_To_v1alpha1_ProviderSpec(in *v1alpha2.ProviderSpec, out *ProviderSpec, s conversion.Scope) error {
	out.Version = in.Version
	if in.Manager != nil {
		in, out := &in.Manager, &out.Manager
		*out = new(ManagerSpec)
		if err := Convert_v1alpha2_ManagerSpec_To_v1alpha1_ManagerSpec(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.Manager = nil
	}
	if in.Deployment != nil {
		in, out := &in.Deployment, &out.Deployment
		*out = new(DeploymentSpec)
		if err := Convert_v1alpha2_DeploymentSpec_To_v1alpha1_DeploymentSpec(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.Deployment = nil
	}
	// WARNING: in.ConfigSecret requires manual conversion: does not exist in peer-type
	out.FetchConfig = (*FetchConfiguration)(unsafe.Pointer(in.FetchConfig))
	out.AdditionalManifestsRef = (*ConfigmapReference)(unsafe.Pointer(in.AdditionalManifestsRef))
	return nil
}

func autoConvert_v1alpha1_ProviderStatus_To_v1alpha2_ProviderStatus(in *ProviderStatus, out *v1alpha2.ProviderStatus, s conversion.Scope) error {
	out.Contract = (*string)(unsafe.Pointer(in.Contract))
	out.Conditions = *(*v1beta1.Conditions)(unsafe.Pointer(&in.Conditions))
	out.ObservedGeneration = in.ObservedGeneration
	out.InstalledVersion = (*string)(unsafe.Pointer(in.InstalledVersion))
	return nil
}

// Convert_v1alpha1_ProviderStatus_To_v1alpha2_ProviderStatus is an autogenerated conversion function.
func Convert_v1alpha1_ProviderStatus_To_v1alpha2_ProviderStatus(in *ProviderStatus, out *v1alpha2.ProviderStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_ProviderStatus_To_v1alpha2_ProviderStatus(in, out, s)
}

func autoConvert_v1alpha2_ProviderStatus_To_v1alpha1_ProviderStatus(in *v1alpha2.ProviderStatus, out *ProviderStatus, s conversion.Scope) error {
	out.Contract = (*string)(unsafe.Pointer(in.Contract))
	out.Conditions = *(*v1beta1.Conditions)(unsafe.Pointer(&in.Conditions))
	out.ObservedGeneration = in.ObservedGeneration
	out.InstalledVersion = (*string)(unsafe.Pointer(in.InstalledVersion))
	return nil
}

// Convert_v1alpha2_ProviderStatus_To_v1alpha1_ProviderStatus is an autogenerated conversion function.
func Convert_v1alpha2_ProviderStatus_To_v1alpha1_ProviderStatus(in *v1alpha2.ProviderStatus, out *ProviderStatus, s conversion.Scope) error {
	return autoConvert_v1alpha2_ProviderStatus_To_v1alpha1_ProviderStatus(in, out, s)
}
